### ISSUE TITLE
Drop Down Option

### ISSUE THREAD

**Issue by cloudbr34k84** [Nerwyn/service-call-tile-feature#60] opened 2024-11-06 05:11 UTC
Do you think its worth while having a drop down option like you can get on some of the tile cards
![image](https://github.com/user-attachments/assets/d9ed9c13-6484-4922-99f6-437c465e3345)

**Comment by Nerwyn** [comment] 2024-11-06 05:35
Duplicate of #56

**Closed** 2024-11-06 05:36 UTC
Labels: duplicate, enhancement
