### ISSUE TITLE
Uncaught TypeError: Cannot set properties of undefined in service-call-tile-feature on Chrome 129.0.0.0

### ISSUE THREAD

**Issue by cloudbr34k84** [Nerwyn/service-call-tile-feature#55] opened 2024-10-17 04:28 UTC
**Description**
Encountered an uncaught error in the Home Assistant frontend while using the service-call-tile-feature custom component. The error occurs on Chrome version 129.0.0.0 running on Windows 10. The issue appears to be related to setting the entity_id in the custom-features-row.min.js file.

Ask: Just wanting to understand what this actually means??

```
Logger: frontend.js.modern.202410023
Source: components/system_log/__init__.py:331
First occurred: 14:24:07 (1 occurrences)
Last logged: 14:24:07

Uncaught error from Chrome 129.0.0.0 on Windows 10
TypeError: Cannot set properties of undefined (setting 'entity_id')
    o (/hacsfiles/service-call-tile-feature/custom-features-row.min.js:2:106121)
    nn.handleSelectorChange (/hacsfiles/service-call-tile-feature/custom-features-row.min.js:14:64399)
    F.handleEvent (/hacsfiles/service-call-tile-feature/custom-features-row.min.js:2:160111)
    dispatchEvent (src/common/dom/fire_event.ts:76:7)
    _setValue (src/components/entity/ha-entity-picker.ts:422:16)
```

Additional Context: This error appears in the custom-features-row.min.js file, specifically when handling the selector change for entities. It might be related to an issue with the ha-entity-picker component.

**Home Assistant Version**
2024.10
Contaner OS

**HACS Version**
4.1.0

**Comment by Nerwyn** [comment] 2024-10-18 22:10
@sipimokus that's a HACS load error, usually resolved by waiting or restarting Home Assistant. It's unrelated to this or this card project in particular.

**Comment by Nerwyn** [comment] 2024-10-18 22:11
@cloudbr34k84 that error means that the custom feature that it's trying to set the entity of is not defined. I thought I caught all situations where that could happen but I may have missed something. Was this a one off issue, or does it happen every time you try to set entity ID?

**Comment by Nerwyn** [comment] 2024-10-25 20:17
I'm going to close this as I can't reproduce it. If you can reproduce it and provide steps to do so, I can reopen and see if there's a fix.

**Closed by Nerwyn** 2024-10-25 20:17 UTC
Labels: bug
